### ISSUE TITLE
Add an Input URL Validator

### ISSUE THREAD

**Issue by dotrachit** [dotrachit/summit#24]
**Describe the bug**
If the user enters a link of the wrong format, our website tries to process it but doesn't give an error message when it fails.

**To Reproduce**
1. Go to https://summit-mlh.vercel.app/
2. Enter a link which is not of the format `https://medium.com/@<username>/<post-id>`
3. Click Submit
4. Nothing will change

**Expected behavior**
An appropriate error message should be displayed telling the user that the link entered is incorrect.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: Catalina 10.15.7

**Comment by routrohan** [comment]
@dotrachit I'll take it up 
Just help me a little here, which file should I put the regex in?

**Comment by dotrachit** [comment]
> @dotrachit I'll take it up
> Just help me a little here, which file should I put the regex in?

You can add the validator in https://github.com/dotrachit/summit/blob/main/src/components/summarizer.js
